[input]
base_directory = "/root/project/output"
html_selector = "main"

[[input.files]]
path = "pages/contato.html"
url = "pages/contato.html"
title = "Contato"

[[input.files]]
path = "pages/sobre-mim.html"
url = "pages/sobre-mim.html"
title = "Sobre Mim"

[[input.files]]
path = "python-101-parte-6.html"
url = "python-101-parte-6.html"
title = "Python 101 - Parte 6 - Estruturas de Repetição - For"

[[input.files]]
path = "tutorial-pelican-2.html"
url = "tutorial-pelican-2.html"
title = "Tutorial de Pelican com Github Pages e CircleCI - 2"

[[input.files]]
path = "python-101-parte-5.html"
url = "python-101-parte-5.html"
title = "Python 101 - Parte 5 - Estruturas de Repetição - While"

[[input.files]]
path = "tutorial-git-1.html"
url = "tutorial-git-1.html"
title = "Tutorial de Git e Github"

[[input.files]]
path = "python-101-parte-4.html"
url = "python-101-parte-4.html"
title = "Python 101 - Parte 4 - Estruturas Condicionais em Python, o Retorno"

[[input.files]]
path = "python-101-parte-3-condicionais.html"
url = "python-101-parte-3-condicionais.html"
title = "Python 101 - Parte 3 - Estruturas Condicionais em Python"

[[input.files]]
path = "tutorial-pelican.html"
url = "tutorial-pelican.html"
title = "Tutorial de Pelican com Github Pages e CircleCI - 1"

[[input.files]]
path = "python-101-parte-2.html"
url = "python-101-parte-2.html"
title = "Python 101 - Segunda Parte"

[[input.files]]
path = "python-101-parte-1.html"
url = "python-101-parte-1.html"
title = "Python 101 - Primeira Parte"

[[input.files]]
path = "porque-pelican.html"
url = "porque-pelican.html"
title = "Porque Pelican"

[[input.files]]
path = "um-novo-comeco.html"
url = "um-novo-comeco.html"
title = "Um novo começo"

[[input.files]]
path = "python-101-parte-6-en.html"
url = "python-101-parte-6-en.html"
title = "Python 101 - Parte 6 - Estruturas de Repetição - For"

[[input.files]]
path = "tutorial-pelican-2-en.html"
url = "tutorial-pelican-2-en.html"
title = "Pelican Tutorial with Github Pages and CircleCI - 2"

[[input.files]]
path = "python-101-parte-5-en.html"
url = "python-101-parte-5-en.html"
title = "Python 101 - Part 5 - Repetition Structures - While"

[[input.files]]
path = "tutorial-git-1-en.html"
url = "tutorial-git-1-en.html"
title = "Tutorial de Git e Github"

[[input.files]]
path = "python-101-parte-4-en.html"
url = "python-101-parte-4-en.html"
title = "Python 101 - Part 4 - Conditionals in Python, the Return"

[[input.files]]
path = "python-101-parte-3-condicionais-en.html"
url = "python-101-parte-3-condicionais-en.html"
title = "Python 101 - part 3 - Python Conditional Structures"

[[input.files]]
path = "tutorial-pelican-en.html"
url = "tutorial-pelican-en.html"
title = "Pelican tutorial with Github Pages and CircleCI - 1"

[[input.files]]
path = "python-101-parte-2-en.html"
url = "python-101-parte-2-en.html"
title = "Python 101 - Segunda Parte"

[[input.files]]
path = "python-101-parte-1-en.html"
url = "python-101-parte-1-en.html"
title = "Python 101 - First Part"

[[input.files]]
path = "porque-pelican-en.html"
url = "porque-pelican-en.html"
title = "Porque Pelican"

[[input.files]]
path = "um-novo-comeco-en.html"
url = "um-novo-comeco-en.html"
title = "A new beggining"