[input]
base_directory = "/root/project/output"
html_selector = "main"

[[input.files]]
path = "pages/contato.html"
url = "pages/contato.html"
title = "Contato"

[[input.files]]
path = "pages/sobre-mim.html"
url = "pages/sobre-mim.html"
title = "Sobre Mim"

[[input.files]]
path = "python-101-parte-1.html"
url = "python-101-parte-1.html"
title = "Python 101 - Primeira Parte"

[[input.files]]
path = "porque-pelican.html"
url = "porque-pelican.html"
title = "Porque Pelican"

[[input.files]]
path = "um-novo-comeco.html"
url = "um-novo-comeco.html"
title = "Um novo começo"

[[input.files]]
path = "python-101-parte-1-en.html"
url = "python-101-parte-1-en.html"
title = "Python 101 - Primeira Parte"

[[input.files]]
path = "porque-pelican-en.html"
url = "porque-pelican-en.html"
title = "Porque Pelican"

[[input.files]]
path = "um-novo-comeco-en.html"
url = "um-novo-comeco-en.html"
title = "A new beggining"