# placeholder

version: 2.1

jobs:
  build:
    docker:
      - image: jcemelanda/programeempython:0.0.3
    steps:
        - checkout
        - run: pip freeze
        - run: make publish
        - run: make github

workflows:
  publish-article:
    jobs:
      - build