version: 2.1

jobs:
  build:
    docker:
      - image: jcemelanda/programeempython:0.0.8
    steps:
        - checkout
        - run: export PATH=/cargo/bin:$PATH; make publish
        - run: make github

workflows:
  publish-article:
    jobs:
      - build