version: 2.1

jobs:
  build:
    docker:
      - image: jcemelanda/programeempython:0.0.7
    steps:
        - checkout
        - run: ls /cargo
        - run: make publish
        - run: make github

workflows:
  publish-article:
    jobs:
      - build